services:
  mysql:
    image: mysql:8.0
    volumes:
      - shareit_db:/var/lib/mysql
    env_file: ./database.env
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

  api:
    depends_on:
      mysql:
        condition: service_healthy 
    build:
      context: .
    ports:
      - "8081:8000"
    env_file: ./.env
    
volumes:
  shareit_db:
